### ISSUE TITLE
Onde?

### ISSUE THREAD

**Issue by aldairandre** [alexhenrique/calculadora#1]
Olá @alexhenrique, estava dando uma olhada no código da sua calculadora e algumas coisas no seu código que me deixaram curioso, eu gostaria de saber onde eu posso encontrar a vídeo aula que te ajudou a fazer essa calculadora ou caso o código seja 100% teu gostaria de trocar algumas ideias sobre a forma de escrita do seu código.

**Comment by alexhenrique** [comment]
É desse curso aqui:
https://www.udemy.com/course/react-redux-pt/
